info:
    description: "CmsNotification REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "CmsNotification"
    version: v1.0
openapi: 3.0.1

components:
    schemas:
        Category:
            description: "Category of the notification"
            properties:
                key:
                    format: int64
                    type: integer
                name:
                    maxLength: 64
                    type: string
            type: object
        Competition:
            description: "Competition type of the notification"
            properties:
                key:
                    format: int64
                    type: integer
                name:
                    maxLength: 64
                    type: string
            type: object
        RegularNotification:
            description: "Regular notification item"
            properties:
                id:
                    format: int64
                    type: integer
                categories:
                    items:
                        $ref: "#/components/schemas/Category"
                    type: array
                competitions:
                    items:
                        $ref: "#/components/schemas/Competition"
                    type: array
                displayDatetime:
                    description: "Format: YYYY-MM-DD HH:MM:SS"
                    type: string
                noticeTitle:
                    maxLength: 128
                    type: string
                isNew:
                    type: boolean
            type: object
        RegularNotificationResponse:
            description: "Response wrapper"
            properties:
                regularNotifications:
                    items:
                        $ref: "#/components/schemas/RegularNotification"
                    type: array
                returnedCount:
                    type: integer
                messageInfo:
                    $ref: "#/components/schemas/MessageInfo"
            type: object
        ErrorResponse:
            properties:
                traceId:
                    type: string
                messageInfo:
                    $ref: "#/components/schemas/MessageInfo"
            type: object
        MessageInfo:
            description: "Message information"
            properties:
                messageId:
                    type: string
                messageBody:
                    type: string
            type: object
paths:
    "/cms-regular-notification":
        get:
            description: "Get latest regular notifications by competition type"
            operationId: getRegularNotification
            parameters:
                - in: query
                  name: competition
                  schema:
                      format: int32
                      type: integer
                - in: query
                  name: limit
                  required: false
                  schema:
                      default: 3
                      format: int32
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/RegularNotificationResponse"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/RegularNotificationResponse"
                    description: "Success"
                400:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/RegularNotificationResponse"
                    description: "Bad Request - Invalid competition parameter"
                500:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/RegularNotificationResponse"
                    description: "Internal Server Error"
                503:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ErrorResponse"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/RegularNotificationResponse"
                    description: "Service Unavaiable"
            tags: ["Notification"]