#
# This is a generated file.
#

api.version=v1.0
openapi.resource=false
openapi.resource.path=/cms-important-notification
osgi.jaxrs.application.select=(osgi.jaxrs.name=CmsImportantNotification)
osgi.jaxrs.resource=true